# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSetup < Formula
  desc "Reproducible Claude Code setup for any repository."
  homepage "https://github.com/jmt-labs/claude-setup"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmt-labs/claude-setup/releases/download/v0.0.2/claude-setup_0.0.2_darwin_arm64.tar.gz"
      sha256 "a200c1533edc3b5118a168bd1464e495b7b30c7f39e3f56dbeed4dedf835d0e1"

      define_method(:install) do
        bin.install "claude-setup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmt-labs/claude-setup/releases/download/v0.0.2/claude-setup_0.0.2_linux_amd64.tar.gz"
      sha256 "b7ae2470c78a03f07f458fd20d00684198c34102c8987d7c25b4c392d4ff25b7"
      define_method(:install) do
        bin.install "claude-setup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmt-labs/claude-setup/releases/download/v0.0.2/claude-setup_0.0.2_linux_arm64.tar.gz"
      sha256 "c70fbf9e259d4985c5a0b5a6b04cb05188f395de3dc6f00e8585f06be652c9fb"
      define_method(:install) do
        bin.install "claude-setup"
      end
    end
  end

  test do
    system "#{bin}/claude-setup", "--version"
  end
end
