# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forgecrate < Formula
  desc "Reproducible Claude Code setup for any repository."
  homepage "https://github.com/jmt-labs/forgecrate"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmt-labs/forgecrate/releases/download/v0.4.0/forgecrate_0.4.0_darwin_arm64.tar.gz"
      sha256 "72c2567549cb23cef6141ab371891010a25a85b7367d41a1467db00046e3b398"

      define_method(:install) do
        bin.install "forgecrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmt-labs/forgecrate/releases/download/v0.4.0/forgecrate_0.4.0_linux_amd64.tar.gz"
      sha256 "f03460719eff90ed3494dc1d1136bbecb820fd9175de24d86e21b1198ad5c2b2"
      define_method(:install) do
        bin.install "forgecrate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmt-labs/forgecrate/releases/download/v0.4.0/forgecrate_0.4.0_linux_arm64.tar.gz"
      sha256 "f2bf03077c27f71c863d62ef91aef06b6271e35593828deaca5fec46e8e4f2a0"
      define_method(:install) do
        bin.install "forgecrate"
      end
    end
  end

  test do
    system "#{bin}/forgecrate", "--version"
  end
end
