# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forgecrate < Formula
  desc "Reproducible Claude Code setup for any repository."
  homepage "https://github.com/jmt-labs/forgecrate"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jmt-labs/forgecrate/releases/download/v0.1.0/forgecrate_0.1.0_darwin_arm64.tar.gz"
      sha256 "9b8f56dc65240c006838254030c91b1dec32edfa5f88d740ba865dc72171a907"

      define_method(:install) do
        bin.install "forgecrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmt-labs/forgecrate/releases/download/v0.1.0/forgecrate_0.1.0_linux_amd64.tar.gz"
      sha256 "a0d9a5fb4b71b0ffb13ea0261c9a08844b99e7ca79fe30345e551581fc76cf02"
      define_method(:install) do
        bin.install "forgecrate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmt-labs/forgecrate/releases/download/v0.1.0/forgecrate_0.1.0_linux_arm64.tar.gz"
      sha256 "7dcb5294c599bf72a3ffa0581b3be34e8b7be30adcfed34ee8c6241f14cdfdab"
      define_method(:install) do
        bin.install "forgecrate"
      end
    end
  end

  test do
    system "#{bin}/forgecrate", "--version"
  end
end
